//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoDauBai
    {
        public int id { get; set; }
        public System.DateTime Ngay { get; set; }
        public string GiangVien { get; set; }
        public string Noidung { get; set; }
        public string NhanXet { get; set; }
        public string DeXuat { get; set; }
    }
}
