//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class BubleT
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int Price { get; set; }
        public string Topping { get; set; }
        public string Note { get; set; }
    }
}
