//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        public int ID { get; set; }
        public Nullable<int> ContactID { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string EmployeeName { get; set; }
    }
}
